### ISSUE TITLE
Error when starting from system service

### ISSUE THREAD

**Issue by hansimglueck** [hansimglueck/teledisko#3]
```
May 12 12:54:37 telepi2 systemd[1]: Started TelediscoFlaskServer.
May 12 12:54:38 telepi2 python3[6990]:  * Serving Flask app 'app'
May 12 12:54:38 telepi2 python3[6990]:  * Debug mode: on
May 12 12:54:38 telepi2 python3[6990]: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
May 12 12:54:38 telepi2 python3[6990]:  * Running on all addresses (0.0.0.0)
May 12 12:54:38 telepi2 python3[6990]:  * Running on http://127.0.0.1:5000
May 12 12:54:38 telepi2 python3[6990]:  * Running on http://10.42.0.63:5000
May 12 12:54:38 telepi2 python3[6990]: Press CTRL+C to quit
May 12 12:54:38 telepi2 python3[6990]:  * Restarting with stat
May 12 12:54:39 telepi2 python3[6991]:  * Debugger is active!
May 12 12:54:39 telepi2 python3[6991]:  * Debugger PIN: 989-884-651
May 12 12:54:50 telepi2 python3[6991]: 10.2.6.184 - - [12/May/2023 12:54:50] "GET / HTTP/1.1" 200 -
May 12 12:54:50 telepi2 python3[6991]: 10.2.6.184 - - [12/May/2023 12:54:50] "GET /static/css/main.css HTTP/1.1" 304 -
May 12 12:54:51 telepi2 python3[6991]: 10.2.6.184 - - [12/May/2023 12:54:51] "GET /WelcomeConfirm HTTP/1.1" 302 -
May 12 12:54:52 telepi2 python3[6991]: 10.2.6.184 - - [12/May/2023 12:54:52] "GET /Really HTTP/1.1" 200 -
May 12 12:54:52 telepi2 python3[6991]: 10.2.6.184 - - [12/May/2023 12:54:52] "GET /static/css/main.css HTTP/1.1" 304 -
May 12 12:54:53 telepi2 python3[6991]: 10.2.6.184 - - [12/May/2023 12:54:53] "GET /ReallyConfirm HTTP/1.1" 302 -
May 12 12:54:53 telepi2 python3[6991]: 10.2.6.184 - - [12/May/2023 12:54:53] "GET /Dsgvo HTTP/1.1" 200 -
May 12 12:54:53 telepi2 python3[6991]: 10.2.6.184 - - [12/May/2023 12:54:53] "GET /static/css/main.css HTTP/1.1" 304 -
May 12 12:54:54 telepi2 python3[6991]: 10.2.6.184 - - [12/May/2023 12:54:54] "GET /DsgvoConfirm HTTP/1.1" 302 -
May 12 12:54:54 telepi2 python3[6991]: 10.2.6.184 - - [12/May/2023 12:54:54] "GET /GetCode HTTP/1.1" 200 -
May 12 12:54:54 telepi2 python3[6991]: 10.2.6.184 - - [12/May/2023 12:54:54] "GET /static/css/main.css HTTP/1.1" 304 -
May 12 12:54:55 telepi2 python3[6991]: 10.2.6.184 - - [12/May/2023 12:54:55] "GET /RotOderBlau HTTP/1.1" 200 -
May 12 12:54:55 telepi2 python3[6991]: 10.2.6.184 - - [12/May/2023 12:54:55] "GET /static/css/main.css HTTP/1.1" 304 -
May 12 12:54:56 telepi2 python3[6991]: 10.2.6.184 - - [12/May/2023 12:54:56] "GET /roteShow HTTP/1.1" 200 -
May 12 12:54:56 telepi2 python3[6991]: 10.2.6.184 - - [12/May/2023 12:54:56] "GET /static/css/main.css HTTP/1.1" 304 -
May 12 12:54:56 telepi2 python3[6991]: [1:16:49.962185030] [7010] #033[1;32m INFO #033[1;37mCamera #033[1;34mcamera_manager.cpp:299 #033[0mlibcamera v0.0.4+22-923f5d70
May 12 12:54:56 telepi2 python3[6991]: [1:16:50.029496018] [7011] #033[1;32m INFO #033[1;37mRPI #033[1;34mraspberrypi.cpp:1476 #033[0mRegistered camera /base/soc/i2c0mux/i2c@1/imx477@1a to Unicam device /dev/media2 and ISP device /dev/media0
May 12 12:54:56 telepi2 python3[6991]: [1:16:50.041646997] [7010] #033[1;32m INFO #033[1;37mCamera #033[1;34mcamera.cpp:1028 #033[0mconfiguring streams: (0) 640x480-XBGR8888
May 12 12:54:56 telepi2 python3[6991]: [1:16:50.042333576] [7011] #033[1;32m INFO #033[1;37mRPI #033[1;34mraspberrypi.cpp:851 #033[0mSensor: /base/soc/i2c0mux/i2c@1/imx477@1a - Selected sensor format: 2028x1520-SBGGR12_1X12 - Selected unicam format: 2028x1520-pBCC
May 12 12:54:56 telepi2 python3[7015]: default: No such process
May 12 12:54:57 telepi2 python3[6991]: Exception in thread Thread-19:
May 12 12:54:57 telepi2 python3[6991]: Traceback (most recent call last):
May 12 12:54:57 telepi2 python3[6991]:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
May 12 12:54:57 telepi2 python3[6991]:     self.run()
May 12 12:54:57 telepi2 python3[6991]:   File "/usr/lib/python3.9/threading.py", line 892, in run
May 12 12:54:57 telepi2 python3[6991]:     self._target(*self._args, **self._kwargs)
May 12 12:54:57 telepi2 python3[6991]:   File "/usr/lib/python3/dist-packages/picamera2/encoders/v4l2_encoder.py", line 200, in thread_poll
May 12 12:54:57 telepi2 python3[6991]:     self.outputframe(b, keyframe, (buf.timestamp.secs * 1000000) + buf.timestamp.usecs)
May 12 12:54:57 telepi2 python3[6991]:   File "/usr/lib/python3/dist-packages/picamera2/encoders/encoder.py", line 238, in outputframe
May 12 12:54:57 telepi2 python3[6991]:     out.outputframe(frame, keyframe, timestamp)
May 12 12:54:57 telepi2 python3[6991]:   File "/usr/lib/python3/dist-packages/picamera2/outputs/ffmpegoutput.py", line 84, in outputframe
May 12 12:54:57 telepi2 python3[6991]:     self.ffmpeg.stdin.write(frame)
May 12 12:54:57 telepi2 python3[6991]: BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by hansimglueck** [comment]
anderer Fehler, wenn es als user service gestartet wird:
```
May 12 12:56:28 telepi2 systemd[730]: Reloading.
May 12 12:56:28 telepi2 systemd[730]: Started Flask Server.
May 12 12:56:29 telepi2 python3[7092]:  * Serving Flask app 'app'
May 12 12:56:29 telepi2 python3[7092]:  * Debug mode: on
May 12 12:56:29 telepi2 python3[7092]: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
May 12 12:56:29 telepi2 python3[7092]:  * Running on all addresses (0.0.0.0)
May 12 12:56:29 telepi2 python3[7092]:  * Running on http://127.0.0.1:5000
May 12 12:56:29 telepi2 python3[7092]:  * Running on http://10.42.0.63:5000
May 12 12:56:29 telepi2 python3[7092]: Press CTRL+C to quit
May 12 12:56:29 telepi2 python3[7092]:  * Restarting with stat
May 12 12:56:31 telepi2 python3[7093]:  * Debugger is active!
May 12 12:56:31 telepi2 python3[7093]:  * Debugger PIN: 127-433-063
May 12 12:56:44 telepi2 python3[7093]: 10.2.6.184 - - [12/May/2023 12:56:44] "GET / HTTP/1.1" 200 -
May 12 12:56:44 telepi2 python3[7093]: 10.2.6.184 - - [12/May/2023 12:56:44] "GET /static/css/main.css HTTP/1.1" 304 -
May 12 12:56:49 telepi2 python3[7093]: 10.2.6.184 - - [12/May/2023 12:56:49] "GET /WelcomeConfirm HTTP/1.1" 302 -
May 12 12:56:49 telepi2 python3[7093]: 10.2.6.184 - - [12/May/2023 12:56:49] "GET /Really HTTP/1.1" 200 -
May 12 12:56:49 telepi2 python3[7093]: 10.2.6.184 - - [12/May/2023 12:56:49] "GET /static/css/main.css HTTP/1.1" 304 -
May 12 12:56:50 telepi2 python3[7093]: 10.2.6.184 - - [12/May/2023 12:56:50] "GET /ReallyConfirm HTTP/1.1" 302 -
May 12 12:56:50 telepi2 python3[7093]: 10.2.6.184 - - [12/May/2023 12:56:50] "GET /Dsgvo HTTP/1.1" 200 -
May 12 12:56:50 telepi2 python3[7093]: 10.2.6.184 - - [12/May/2023 12:56:50] "GET /static/css/main.css HTTP/1.1" 304 -
May 12 12:56:50 telepi2 python3[7093]: 10.2.6.184 - - [12/May/2023 12:56:50] "GET /DsgvoConfirm HTTP/1.1" 302 -
May 12 12:56:51 telepi2 python3[7093]: 10.2.6.184 - - [12/May/2023 12:56:51] "GET /GetCode HTTP/1.1" 200 -
May 12 12:56:51 telepi2 python3[7093]: 10.2.6.184 - - [12/May/2023 12:56:51] "GET /static/css/main.css HTTP/1.1" 304 -
May 12 12:56:52 telepi2 python3[7093]: 10.2.6.184 - - [12/May/2023 12:56:52] "GET /RotOderBlau HTTP/1.1" 200 -
May 12 12:56:52 telepi2 python3[7093]: 10.2.6.184 - - [12/May/2023 12:56:52] "GET /static/css/main.css HTTP/1.1" 304 -
May 12 12:56:53 telepi2 python3[7093]: 10.2.6.184 - - [12/May/2023 12:56:53] "GET /roteShow HTTP/1.1" 200 -
May 12 12:56:53 telepi2 python3[7093]: 10.2.6.184 - - [12/May/2023 12:56:53] "GET /static/css/main.css HTTP/1.1" 304 -
May 12 12:56:53 telepi2 python3[7093]: [1:18:46.841897829] [7115] #033[1;32m INFO #033[1;37mCamera #033[1;34mcamera_manager.cpp:299 #033[0mlibcamera v0.0.4+22-923f5d70
May 12 12:56:53 telepi2 python3[7093]: [1:18:46.874693128] [7116] #033[1;32m INFO #033[1;37mRPI #033[1;34mraspberrypi.cpp:1476 #033[0mRegistered camera /base/soc/i2c0mux/i2c@1/imx477@1a to Unicam device /dev/media2 and ISP device /dev/media0
May 12 12:56:53 telepi2 python3[7093]: [1:18:46.880748664] [7115] #033[1;32m INFO #033[1;37mCamera #033[1;34mcamera.cpp:1028 #033[0mconfiguring streams: (0) 640x480-XBGR8888
May 12 12:56:53 telepi2 python3[7093]: [1:18:46.881276914] [7116] #033[1;32m INFO #033[1;37mRPI #033[1;34mraspberrypi.cpp:851 #033[0mSensor: /base/soc/i2c0mux/i2c@1/imx477@1a - Selected sensor format: 2028x1520-SBGGR12_1X12 - Selected unicam format: 2028x1520-pBCC
May 12 12:56:53 telepi2 python3[7120]: Guessed Channel Layout for Input Stream #0.0 : stereo
May 12 12:56:54 telepi2 python3[7120]: static/videos/test-20230512-125653.mp4: No such file or directory
May 12 12:56:54 telepi2 python3[7093]: Exception in thread Thread-19:
May 12 12:56:54 telepi2 python3[7093]: Traceback (most recent call last):
May 12 12:56:54 telepi2 python3[7093]:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
May 12 12:56:54 telepi2 python3[7093]:     self.run()
May 12 12:56:54 telepi2 python3[7093]:   File "/usr/lib/python3.9/threading.py", line 892, in run
May 12 12:56:54 telepi2 python3[7093]:     self._target(*self._args, **self._kwargs)
May 12 12:56:54 telepi2 python3[7093]:   File "/usr/lib/python3/dist-packages/picamera2/encoders/v4l2_encoder.py", line 200, in thread_poll
May 12 12:56:54 telepi2 python3[7093]:     self.outputframe(b, keyframe, (buf.timestamp.secs * 1000000) + buf.timestamp.usecs)
May 12 12:56:54 telepi2 python3[7093]:   File "/usr/lib/python3/dist-packages/picamera2/encoders/encoder.py", line 238, in outputframe
May 12 12:56:54 telepi2 python3[7093]:     out.outputframe(frame, keyframe, timestamp)
May 12 12:56:54 telepi2 python3[7093]:   File "/usr/lib/python3/dist-packages/picamera2/outputs/ffmpegoutput.py", line 84, in outputframe
May 12 12:56:54 telepi2 python3[7093]:     self.ffmpeg.stdin.write(frame)
May 12 12:56:54 telepi2 python3[7093]: BrokenPipeError: [Errno 32] Broken pipe
```
